### ISSUE TITLE
`sails generate ember-blueprints` failed with code 1

### ISSUE THREAD

**Issue by jhliberty** [mphasize/sails-generate-ember-blueprints#28]
Ran into this error when trying to setup a new sails/ember project. Any suggestions? 

```
[server]$ npm install sails-generate-ember-blueprints
sails-generate-ember-blueprints@0.0.5 node_modules/sails-generate-ember-blueprints
├── pluralize@1.1.2
├── merge-defaults@0.2.1 (lodash@2.4.1)
└── lodash@3.2.0
[server]$ sails generate ember-blueprints
Running generator (sails-generate-ember-blueprints) @ `/Users/jhliberty/work/Seeds-Master/DesiredResult/medicoreo/server`...
Installing "basic" of blueprints.
fs.js:521
  if (typeof m === 'string')
               ^
Error: ENOENT: no such file or directory, open '/Users/jhliberty/work/Seeds-Master/DesiredResult/medicoreo/server/api/blueprints/create.js'
    at Error (native)
    at Object.fs.openSync (fs.js:546:18)
    at Object.fs.writeFileSync (fs.js:1147:15)
    at /Users/jhliberty/work/Seeds-Master/DesiredResult/medicoreo/server/node_modules/sails-generate-ember-blueprints/lib/index.js:36:14
    at Array.forEach (native)
    at Object.module.exports.targets../.exec (/Users/jhliberty/work/Seeds-Master/DesiredResult/medicoreo/server/node_modules/sails-generate-ember-blueprints/lib/index.js:35:72)
    at afterwards (/Users/jhliberty/.nvm/versions/io.js/v1.6.2/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:61:23)
    at Object.async.until (/Users/jhliberty/.nvm/versions/io.js/v1.6.2/lib/node_modules/sails/node_modules/sails-generate/node_modules/async/lib/async.js:655:13)
    at generateTarget (/Users/jhliberty/.nvm/versions/io.js/v1.6.2/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:39:9)
    at /Users/jhliberty/.nvm/versions/io.js/v1.6.2/lib/node_modules/sails/node_modules/sails-generate/lib/generate.js:155:11

```

**Comment by mphasize** [comment]
Related to #27 ... looks like the /api/blueprints directory is missing. Fix is coming soon, until then you can create the directory manually. Cheers!
